apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: builds.kpack.io
spec:
  group: kpack.io
  preserveUnknownFields: false
  versions:
  - name: v1alpha1
    served: true
    storage: false
  - name: v1alpha2
    served: true
    storage: true
  conversion:
    strategy: Webhook
    webhookClientConfig:
      service:
        namespace: kpack
        name: kpack-webhook
        path: /convert
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          x-kubernetes-preserve-unknown-fields: true
        status:
          x-kubernetes-preserve-unknown-fields: true
  names:
    kind: Build
    singular: build
    plural: builds
    shortNames:
    - cnbbuild
    - cnbbuilds
    - bld
    - blds
    categories:
    - kpack
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: Image
    type: string
    JSONPath: ".status.latestImage"
  - name: Succeeded
    type: string
    JSONPath: #@ ".status.conditions[?(@.type==\"Succeeded\")].status"
