apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: images.kpack.io
spec:
  group: kpack.io
  preserveUnknownFields: false
  versions:
  - name: v1alpha1
    served: true
    storage: false
  - name: v1alpha2
    served: true
    storage: true
  conversion:
    strategy: Webhook
    webhookClientConfig:
      service:
        namespace: kpack
        name: kpack-webhook
        path: /convert
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          x-kubernetes-preserve-unknown-fields: true
        status:
          x-kubernetes-preserve-unknown-fields: true
  names:
    kind: Image
    singular: image
    plural: images
    shortNames:
    - cnbimage
    - cnbimages
    - img
    - imgs
    categories:
    - kpack
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: LatestImage
    type: string
    JSONPath: ".status.latestImage"
  - name: Ready
    type: string
    JSONPath: #@ ".status.conditions[?(@.type==\"Ready\")].status"
